### ISSUE TITLE
Percentage Bars of Content

### ISSUE THREAD

**Issue by coyote-0** [dojohnso/infinitybottlesclub#8]
The percentage bars for each content addition currently reads as a percent of the whole bottle. It would be more useful if the percentage was of the total current content, not of the potential content.  Example, in one liter bottle, two additions of 5oz each shows 30% full on the bottle.  This is useful, but each content addition shows 15% each, which is each percentage of the whole bottle capacity.  It should show 50% each so I know when I drink some, how much of that drink is each addition. If I added another 5 oz for a third addition, it would show 45% full and 33% for each addition.  The content additions should always add to 100, regardless of how full or empty the bottle is.

**Comment by dojohnso** [comment]
I'm modifying the view so both are visible. The primary bar will now be the % of the mixture (ie 2 equal addition sizes will each show 50%, no matter the size of the bottle), and below that will be a lighter, smaller bar with the % of the bottle.

screenshot example: 
![image](https://user-images.githubusercontent.com/294549/92774411-105c0780-f363-11ea-8764-8602e924b2a5.png)
